title: RijksData
description: Documentation for Rijksmuseum data services
markdown: kramdown
search_enabled: true
remote_theme: pmarsceill/just-the-docs
logo: "/assets/css/logo.png"
aux_links:
  "RijksData on www.rijksmuseum.nl":
    - "https://www.rijksmuseum.nl/en/data"
plugins:
  - jekyll-redirect-from
